version: '3'
services:

  app:
    build: .
    restart: always
    depends_on:
    - mongodb
    ports:
     - "3030:3030"
     - "8080:8080"
    command: "npm run dev"
    volumes:
     - "./src:/var/www/app/src"

  mongodb:
    image: mongo:3.4
